 /******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the ULTRASONIC driver
 *
 * Author: Omar Saad
 *
 *******************************************************************************/

#include "std_types.h"
#include "gpio.h"

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define ULTRASOINC_TRIGGER_PORT_ID  PORTB_ID
#define ULTRASOINC_TRIGGER_PIN_ID  PIN5_ID  /*TRIGGER connected to PB5 in PORTB */

#define ULTRASOINC_ECHO_PORT_ID  PORTD_ID
#define ULTRASOINC_ECHO_PIN_ID  PIN6_ID /*ECHO connected to PD6 in PORTD */

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description : Function to initialize the ULTRASONIC driver
 * 	1. Initialize the ICU driver.
 * 	2. Setup the ICU call back function.
 * 	3. Setup the direction for the trigger pin as output
 */
void Ultrasonic_init(void);
/*
 * Description :
 * Function to Send the Trigger pulse to the ULTRASONIC.
 */
void Ultrasonic_Trigger(void);
/*
 * Description :Function to read Distance from UltraSonic
 * 1. Initialize the UltraSonic driver
 * 2. Send the Trigger pulse to the ULTRASONIC.
 * 2. Start the measurements by the ICU
 * 4. deInitialize ICU driver
 * 5. return distance value
 */
uint16 Ultrasonic_readDistance(void);
/*
 * Description : Call back Function of ICU
 * Calculates the pulse time generated by the UltraSonic sensor.
 */
void Ultrasonic_edgeProcessing(void);


#endif /* ULTRASONIC_H_ */
