/******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the ULTRASONIC driver
 *
 * Author: Omar Saad
 *
 *******************************************************************************/

#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include "avr/io.h"
#include <util/delay.h> /* For the delay functions */

/*******************************************************************************
 *                      Global Variables                                *
 *******************************************************************************/

uint8 g_edgeCount = 0;
uint16 g_timeEchoHigh = 0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description : Function to initialize the ULTRASONIC driver
 * 	1. Initialize the ICU driver.
 * 	2. Setup the ICU call back function.
 * 	3. Setup the direction for the trigger pin as output
 */
void Ultrasonic_init(void)
{

	/* Create configuration structure for ICU driver */
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};
	/* Enable Global Interrupt I-Bit */
	SREG |= (1<<7);
	/* Set the Call back function pointer in the ICU driver */
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	/* Initialize ICU driver */
	Icu_init(&Icu_Config);

	/*
	 * Setup direction for trigger pin as OUTPUT
	 */
	GPIO_setupPinDirection(ULTRASOINC_TRIGGER_PORT_ID, ULTRASOINC_TRIGGER_PIN_ID, PIN_OUTPUT);
}

/*
 * Description :
 * Function to Send the Trigger pulse to the ULTRASONIC.
 */
void Ultrasonic_Trigger(void)
{
	/* Trigger ultrasonic by sending pulse to trigger pin for 10 us*/
	GPIO_writePin(ULTRASOINC_TRIGGER_PORT_ID, ULTRASOINC_TRIGGER_PIN_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASOINC_TRIGGER_PORT_ID, ULTRASOINC_TRIGGER_PIN_ID, LOGIC_LOW);
}
/*
 * Description :Function to read Distance from UltraSonic
 * 1. Initialize the UltraSonic driver
 * 2. Send the Trigger pulse to the ULTRASONIC.
 * 2. Start the measurements by the ICU
 * 4. deInitialize ICU driver
 * 5. return distance value
 */
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance;
	Ultrasonic_init();
	Ultrasonic_Trigger();
	g_edgeCount = 0;
	/* polling until edge count reaches 2 to calculate time by ICU*/
	while(g_edgeCount!=2);
	/* Calculate distance from time */
	distance =g_timeEchoHigh/58;
	/* Disable ICU Driver */
	Icu_DeInit();
	return distance;
}
/*
 * Description : Call back Function of ICU
 * Calculates the pulse time generated by the UltraSonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge to calculate time of HIGH echo
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeEchoHigh = Icu_getInputCaptureValue();

		/* Clear the timer counter register to start measurements again */
		Icu_clearTimerValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
	}
}

